trigger: none

variables:
  tag: '$(Build.BuildId)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--collect "Code coverage"'
  displayName: 'dotnet test'